name: Déploiement Ionos FTP
on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    name: Déploiement
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Récupération du code
        uses: actions/checkout@v4

      - name: 🚀 Envoi sur Ionos via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "."
          target: ${{ secrets.FTP_SERVER_DIR }}