name: Déploiement Ionos FTP
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Déploiement
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Récupération du code
        uses: actions/checkout@v4

      - name: 🚀 Envoi sur Ionos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}